### PR TITLE
group dependabot updates

### PR DESCRIPTION
**Pull request by cpanato**

### CODE REVIEW

**Comment by rikatz** [comment]
/lgtm
/approve
I dont have github on this celphone yet so go for it and merge it :P

Em seg., 6 de nov. de 2023 às 07:10, Carlos Tadeu Panato Junior <
***@***.***> escreveu:

**Comment by cpanato** [comment]
@rikatz you need to approve the pr and not use the /approve lol

**Comment by rikatz** [comment]
Damn github that does not allow ne to approve via email

“I, Ricardo Katz, hereby approve Carlos Panato to merge this PR”
Chicago, IL, 6th of November of 2023

Bow seriously once I’m with my computer I will approve it

Em seg., 6 de nov. de 2023 às 07:17, Carlos Tadeu Panato Junior <
***@***.***> escreveu:

**Review by rikatz — APPROVED** [review]

**Comment by rikatz** [comment]
Done

**Pull request merged**
